{
 "title": "UPS",
 "description": "Monitor your UPS over NUT service. Uses HON95/prometheus-nut-exporter ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   { "name": "data_source", "query": "prometheus" },
   { "name": "kWhCost", "label": "The cost in pence per kWh", "query": "21.98" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({ups=\"$ups\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage_volts{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_charge{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Emergency Runtime Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=~\"${ups:pipe}\",instance=\"${instance}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Cost: 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[1d])/1000) * (${kWhCost}) /100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Daily Cost (1 Month)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[30d])/30/1000) * (${kWhCost}) /100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost: 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[30d])/1000) * (${kWhCost}) /100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[365d])/12/1000) * (${kWhCost}) /100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost: 365 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[365d])/1000) * (${kWhCost}) /100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost per kWh (p)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "${kWhCost}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Charge [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(nut_battery_charge{ups=~\"${ups:pipe}\",instance=\"${instance}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Current"
    },
    {
     "expr": "100 * avg_over_time(nut_battery_charge_low{ups=~\"${ups:pipe}\",instance=\"${instance}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Low"
    }
   ]
  },
  {
   "title": "Status Change",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nut_ups_status{status=~\"OL|OB|LB\", instance=\"$instance\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{ups=~\"${ups:pipe}\",instance=\"${instance}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{ups=~\"${ups:pipe}\",instance=\"${instance}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load (Watts) [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_load{ups=~\"${ups}\",instance=\"${instance}\"}[$smoothing_interval]) * 850",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "nut_ups_info{instance=\"$instance\"}"
    }
   ]
  }
 ]
}